SELECT 
    DF.ID_FACTURA,
    C.NOMBRE_CLI || ' ' || C.APELLIDO_CLI AS NOMBRE_CLIENTE,
    E.NOMBRE_EMP || ' ' || E.APELLIDO_EMP AS NOMBRE_EMPLEADO,
    CG.NOMBRE_CARGO AS CARGO_EMPLEADO,
    P.NOMBRE_PROD AS PRODUCTO,
    P.PRECIO_UNIT AS PRECIO_UNITARIO,
    DF.CANTIDAD AS TOTAL_CANTIDAD
FROM 
    DETALLE_FACTURA DF
JOIN 
    FACTURA F ON DF.ID_FACTURA = F.ID_FACTURA
JOIN 
    CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
JOIN 
    EMPLEADO E ON E.ID_EMPLEADO = E.ID_EMPLEADO
JOIN
    CARGO CG ON E.ID_CARGO = CG.ID_CARGO
JOIN 
    PRODUCTO P ON DF.ID_PRODUCTO = P.ID_PRODUCTO
ORDER BY 
    DF.ID_FACTURA ASC;



